name: CI/CD Demo

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest tests --maxfail=1 --disable-warnings -q

    # --- Docker build steps (commented for future reference) ---
    # - name: Build Docker image
    #   run: docker build -t ml-fastapi-app .
    #
    # - name: Verify Docker image
    #   run: docker run --rm ml-fastapi-app --help
